### ISSUE TITLE
bug - image templating does not evalutate defaults in proper order

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#10]
base
```
global:
  applicationName: uni-backend
  customerName: asi
  image:
    defaultImageRegistry: registry.gamewarden.io
    defaultImageRepository: air-space-intelligence
```

dev 
```
microservices:
  web:
    image:
      name: uni-backend
      tag: 1.0.0
```

helm template uni-backend ../../uchart -f base.yaml -f dev.yaml
Error: template: uchart/templates/deployment.yaml:11:31: executing "uchart/templates/deployment.yaml" at <$v.image.repository>: nil pointer evaluating interface {}.repository

The templates (in all of them, not just deployment) requires the repository to be set on each microsvc before it will even consider the defaults
