### ISSUE TITLE
[bug] cronjob security context templates incorrectly

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#12]
major bug in the cronJobs template (maybe others now?)

`{{- $securityContext := $v.securityContext | default (dict "capabilities" (dict "drop" (list "ALL"))) }}`

this does not render properly, even if I try to specify it.
```
      template:
        spec:
          containers:
            - capabilities:
                drop:
                  - ALL
              command:
```
or if I try to add it in the values as a workaround it results in
```
              securityContext:
              capabilities:
              - drop:
                - ALL
```
