### ISSUE TITLE
[bug] subcharts do not properly pass values to the dependent helm chart

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#23]
```
  subCharts:    
    redis:
      enabled: true
      chart: redis
      revision: '17.9.5'
      project: asi-dev-asi
      namespace: uni-flight-tracks
      values:
        fullnameOverride: redis
        image:
          repository: registry.gamewarden.io/air-space-intelligence/redis
          tag: 7.2.3-hardened
        resources:
          requests:
            cpu: '0.18'
            memory: 70Mi
```

Using this template only globals are showing up in the resulting subchart wrapper app. On inspection of the template, it seems to only be checking for `global` keys and ignores the others.

This is a blocker.
