### ISSUE TITLE
support job to dynamically create secrets

### ISSUE THREAD

**Issue by drduker** [second-front/uchart#35]
something like below were you can generate any type of secret in the secret spec to cover all the use cases, multiple secrets and any number of unique keys.  And that can generate based on the values inputted to the release?
```
generate-secrets-job:
  secretNameHere:
    username: rand64
    password: rand64
  certificate:
      {{- $ca := genCA "harbor-token-ca" 365 }}... like in helm

```
