### ISSUE TITLE
[bug] subcharts creates Application resource multiple times

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#4]
Enabling a subchart causes 2 different templates in argocd_wrappers to create Applications, with different names - which will lead to some interesting argocd syncs :) 

`Application.yaml`
```yaml
{{- if .Values.subCharts }}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}-{{ .Values.global.applicationName }}"
  namespace: argocd
```

`SubCharts.yaml`
```yaml
{{- if .Values.subCharts }}
  {{- range $subChart, $v := .Values.subCharts}}
  {{- with $ -}}
  {{ if not (empty $v) }}
  {{ if not (eq $v.enabled false) }}

{{/* Variables */}}
{{- $name := $v.name | default $subChart }}
{{- $chartUrl := $v.chartUrl | default "registry.gamewarden.io/charts" }}
{{- $namespace := $v.namespace | default .Values.global.applicationName }}
{{- $revision := $v.revision }}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}-{{ .Values.global.applicationName }}-{{ $subChart }}"
  namespace: argocd
```
