### ISSUE TITLE
[bug] Job template pulling config variables from unexpected location

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#40]
https://github.com/second-front/uchart/blob/744cbe163c17e2b9558ba37ed1909e52d1e49a24/templates/job.yaml#L10-L13

We had expected that Job specific vars like `backoffLimit` or `parallelism` were subordinate to the `microservices.x.job` field but the template is pulling them from the `microservices.x` level. This seems like an oversight. I had just noticed that our Jobs all have the defaults assigned as a result.

**Comment by drduker** [comment]
microservices at $v are the job.


So you should be able to set a job like this:

microservices:
  job-one:
    backoffLimit: "6"

**Comment by drduker** [comment]
job and crontab spec things are all under the cronjob and job key now.

```
mircoservices:
  job:
    enabled:
      successfulJobsHistoryLimit: 7
      failedJobsHistoryLimit: 77
      backoffLimit: 7
```
