### ISSUE TITLE
[feature request] HPA templating for behavior

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#41]
HPA v2 API includes scaleUp/scaleDown policy behaviors to all fine grained control. For example, may want to scale up quickly but hold those pods, once started, for a longer period of time as a precaution against churn.

Because the `behavior` block is so varied, we suggest that you just template it as a full yaml block input. 
```
      autoscaling:
        enabled: true
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
              - type: Percent
                value: 10
                periodSeconds: 60
          scaleUp:
            policies:
              - type: Percent
                value: 200
                periodSeconds: 60
        minReplicas: 80
        maxReplicas: 500
```
