### ISSUE TITLE
Setting securityContext overwrites values from all previous microservices

### ISSUE THREAD

**Issue by matt-conway-airspace-intelligence** [second-front/uchart#42]
Given a list of microservices, it appears that the securityContext field is overwritten for each microservice with later ones taking precedence. This can cause unexpected behavior. Here's a simple values example to reproduce:

```yaml
uchart:
  argocd:
    wrapperAppOff: true
    createProject: false

  microservices:
    statsd-relay:
      daemonset:
        enabled: true
      image:
        name: statsd-relay
        tag: latest
      securityContext:
        runAsUser: 65532

    statsd:
      statefulset:
        enabled: true
      replicaCount: 4
      image:
        name: statsd
        tag: latest

    graphite-backend:
      replicaCount: 1
      strategy:
        type: Recreate
      image:
        name: go-carbon
        tag: latest
      securityContext:
        runAsUser: 65532
      podSecurityContext:
        fsGroup: 65532

    graphite-api:
      replicaCount: 2
      image:
        name: carbonapi
        tag: latest
      securityContext:
        runAsUser: 65532

    carbon-relay-ng:
      deployment:
        enabled: true
      image:
        name: grafana/carbon-relay-ng
        tag: latest
      securityContext:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
```

With this config I'd expect `runAsNonRoot` to be templated to false only for the carbon-relay-ng deployment, and the rest of the of the microservices to have true, given that's the default. However, `runAsNonRoot` is templated to false for all microservices prior to carbon-relay-ng, in this case all of them. This precedence behavior can be seen if you set `runAsNonRoot` to true for graphite-backend, then all microservices before it will have true, whereas graphite-api and carbon-relay-ng will have false.

**Comment by drduker** [comment]
Yes, i see that when templated from main, carbon-relay-ng is overritting securityContext for the rest of the templates:
current:
```

statsd-relay:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 65532
carbon-relay-ng:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
graphite-api:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 65532
graphite-backend:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 65532
statsd:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
```
