### ISSUE TITLE
[bug] microservices.X.service.enabled: false does not disable the Service template

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#7]
Seem unable to disable the Service template. 

Sample minimal values:
```yaml
global:
  applicationName: uni-backend
  customerName: air-space-intelligence
  image:
    defaultImageRepository: air-space-intelligence
    defaultName: uni-backend
  namespace: uni-backend

microservices:
  web:
    appLabel: web
    image:
      name: uni-backend
      tag: 1.0.0
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        memory: 1Gi
    service:
      enabled: false
```

This should result in no Service but I still get one in the output.
